name: Deploy Documentation to GitHub Pages

# Aciona o workflow quando houver um push nas branches 'thiago' ou 'ryan'
on:
  push:
    branches:
      - thiago
      - ryan

# Permissões para o GITHUB_TOKEN
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Faz o checkout do repositório para ter acesso aos commits e branches
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Precisamos buscar todo o histórico para poder alternar entre as branches
          fetch-depth: 0 

      # 2. Configura o Git para poder fazer commits em nome do 'github-actions[bot]'
      - name: Setup Git User
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # 3. Cria ou muda para a branch 'gh-pages', limpando o conteúdo antigo
      - name: Switch to gh-pages branch
        run: |
          git checkout --orphan gh-pages
          git rm -rf .

      # 4. Puxa a pasta de documentação da branch 'thiago'
      - name: Copy notes from thiago's branch
        run: git checkout thiago -- docs/thiago

      # 5. Puxa a pasta de documentação da branch 'ryan'
      - name: Copy notes from ryan's branch
        run: git checkout ryan -- docs/ryan
      
      # 6. Cria uma página inicial simples com links para os arquivos
      - name: Create index page
        run: |
          echo '# Anotações do Projeto' > index.md
          echo '' >> index.md
          echo '## Anotações de Thiago' >> index.md
          # Verifica se a pasta existe antes de tentar listar os arquivos
          if [ -d "docs/thiago" ]; then
            for file in $(find docs/thiago -name "*.md"); do
              filename=$(basename "$file" .md)
              echo "- [${filename}](${file})" >> index.md
            done
          fi
          echo '' >> index.md
          echo '## Anotações de Ryan' >> index.md
          # Verifica se a pasta existe antes de tentar listar os arquivos
          if [ -d "docs/ryan" ]; then
            for file in $(find docs/ryan -name "*.md"); do
              filename=$(basename "$file" .md)
              echo "- [${filename}](${file})" >> index.md
            done
          fi

      # 7. Faz o commit e o push dos arquivos consolidados para a branch 'gh-pages'
      - name: Commit and Push to gh-pages
        run: |
          git add .
          # O '|| exit 0' evita que o workflow falhe se não houver mudanças
          git commit -m "Deploy docs to gh-pages" || exit 0
          git push -u origin gh-pages --force
